[tool.poetry]
name = "Wheater App"
version = "0.1.0"
description = ""
authors = ["Admin <admin@netmin.ru>"]

[tool.poetry.dependencies]
python = "^3.9"
uvicorn = "^0.13.3"
fastapi = "^0.63"
httpx = "^0.16.1"
Jinja2 = "^2.11.2"
aiofiles = "^0.6.0"
